version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=docspert_health_task
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Ahmed2000-

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_DB=docspert_health_task
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Ahmed2000-
      - POSTGRES_HOST=127.0.0.1
      - POSTGRES_PORT=5432

volumes:
  postgres_data:

