version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: docspert_health_task
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Ahmed2000-

  web:
    build:
    # context: .  # Build context is the current directory
    
    command: python manage.py migrate && python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./Docspert_Health:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_NAME=docspert_health_task
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=Ahmed2000-
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
volumes:
  postgres_data:
