# Generated by Django 5.0.7 on 2024-07-16 22:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='api_account_name_ea4177_idx')],
            },
        ),
        migrations.CreateModel(
            name='CsvFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='Csv_files/')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('auth', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded'],
                'indexes': [models.Index(fields=['-uploaded'], name='api_csvfile_uploade_61d3db_idx')],
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trans_time', models.DateTimeField(auto_now_add=True)),
                ('accounts_from', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_from', to='api.account')),
                ('accounts_to', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_to', to='api.account')),
            ],
            options={
                'ordering': ['-trans_time'],
                'indexes': [models.Index(fields=['-trans_time'], name='api_transfe_trans_t_4fdca4_idx')],
            },
        ),
    ]
