# Generated by Django 5.0.7 on 2024-07-16 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='accounts_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_from', to='api.account'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='accounts_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_to', to='api.account'),
        ),
    ]
